### ISSUE TITLE
Question, why no kubernetes within kubernetes?

### ISSUE THREAD

**Issue by lknite** [siderolabs/sidero#891]
Had the thought the other day that a kubernetes cluster could be spun up within a kubernetes cluster via pods.  Yet, though I've found a couple blogs which have experimented, I haven't found a supported project.  Instead, I've found projects like this one, which uses vms to spin up clusters.

Is there a reason why kubernetes within kubernetes isn't being used?  All the benefits of kubernetes would apply, like if you wanted 3 control plane nodes you could modify replicas in a yaml and two more pods would spin up ... and kubernetes would use its algorithms to place the pod in a good location on the bare metal clusters to spin up the pod.  Not using vms, but pods.

**Comment by bzub** [comment]
I think the concept of "nested clusters" has quite a lot of interest and development nowadays. Talos and Sidero fit in well by supporting deployment to bare-metal as the foundation for virtual clusters. Since Talos supports running on all environments including containers, it's not a big leap to then run Talos in a StatefulSet as you describe.

Talos + Sidero cluster-api providers let you define/provision bare-metal via Kubernetes resources. Supporting nested clusters first-class with the same OS/tools might take the form of Sidero implementing features similar to [cluster-api-provider-nested](https://github.com/kubernetes-sigs/cluster-api-provider-nested). For now, though, it's relatively simple to [create a nested cluster](https://github.com/bzub/tink) by hand so to speak.

**Comment by lknite** [comment]
Thank you.  I've got a better grasp on what sidero does, and am very close to wiping out my servers and replacing them with sidero, as I was thinking to wipe them out and just install linux and deploy my own kubernetes to them bare metal.  Sidero with its talos implementation sounds much safer and cleaner and well, it is good to avoid reinventing the wheel.

Since this message I have come across vcluster and capsule, as well as tink.  I do have a requirement for a gitops based solution, so something yaml which can be deployed via argocd/flux.

So far it seems like vcluster might be the right solution for now.  I've been thinking about my one kubernetes cluster which I do have exposed to the internet, and how that would work as a vcluster.  I'm not sure if would be safe as my current vm based system which is on an isolated network.  Maybe I just need a separate physical box for said cluster.

Thanks for your help on this one.
